# Default Terminology Library Configuration
# License-free terminology sources only
#
# For licensed systems (SNOMED CT, LOINC, RxNorm, CPT, etc.),
# mount your own config/ volume with a customized library.yml.

base:
  url: https://storage.googleapis.com/tx-fhir-org

sources:
  # Built-in code systems
  - internal:lang
  - internal:country
  - internal:currency
  - internal:mimetypes

  # UCUM - Unified Code for Units of Measure
  # - ucum:data/terminology-cache/ucum-essence-2.2.xml

  # SNOMED CT (International Edition)
  - snomed!:sct_intl_20260601.cache
  - snomed:sct_ch_20260607.cache

  # LOINC (Logical Observation Identifiers Names and Codes)
  - loinc:Loinc_2.82.db

  # Other FHIR packages
  - npm:ch.fhir.ig.ch-term#3.3.0
  - npm:ch.fhir.ig.ch-vacd#6.0.0
  - npm:ch.fhir.ig.ch-epreg#1.0.0
  - npm:ch.fhir.ig.ch-epl#1.0.0
  - npm:ch.fhir.ig.ch-elm#1.13.1
  - npm:ch.fhir.ig.ch-crl#0.9.0
  - npm:ch.fhir.ig.ch-ems#1.9.0

